version: '3.9'
services: 
    app:
        build: .
        volumes: 
            - .:/backend
        ports: 
            - 8000:8000
        image: backend:django
        container_name: backend_container
        command: python manage.py runserver 0.0.0.0:8000