# Generated by Django 3.2.5 on 2021-08-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210813_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dated_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
