# Generated by Django 3.2.5 on 2021-08-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_dated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
